In [2]:
import numpy, soundfile
from scipy import signal
import torch

import torch.nn as nn
import torch.nn.functional as F

length = 200 * 160 + 240
audio, _ = soundfile.read('6.wav')
audio = audio[: length]
audio = numpy.stack([audio], axis=0)
rir, _ = soundfile.read('Room200-00001.wav')
rir = numpy.expand_dims(rir.astype(numpy.float), 0)
rir = rir / numpy.sqrt(numpy.sum(rir ** 2))
audio = signal.convolve(audio, rir, mode='full')[:, :length]
audio = torch.FloatTensor(audio[0])
inp = audio.unsqueeze(0)
inp = inp.unsqueeze(0)
print(inp)
inp = inp + inp
inp



tensor([[[1.7544e-18, 8.7721e-19, 1.0527e-18,  ..., 1.1737e-03,
          8.4053e-04, 8.8358e-04]]])


C:\Users\Kan\AppData\Local\Temp\ipykernel_3356\668286731.py:13: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  rir = numpy.expand_dims(rir.astype(numpy.float), 0)


tensor([[[3.5089e-18, 1.7544e-18, 2.1053e-18,  ..., 2.3473e-03,
          1.6811e-03, 1.7672e-03]]])

In [11]:
"""
one_hot = torch.zeros(10, 5000, 160)
label = torch.ones(10)
one_hot.scatter_(1, label.view(-1, 1), 1)
"""
x = torch.rand(2, 5)
y = torch.zeros(3, 5)
print(x)
print(y)
print(torch.LongTensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]]))
y.scatter_(0, torch.LongTensor([[0, 1, 2, 0, 0], [2, 0, 0, 1, 2]]), 1)

tensor([[0.1572, 0.2671, 0.4133, 0.8402, 0.9865],
        [0.4575, 0.4984, 0.4658, 0.6764, 0.0887]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0, 1, 2, 0, 0],
        [2, 0, 0, 1, 2]])


tensor([[1., 1., 1., 1., 1.],
        [0., 1., 0., 1., 0.],
        [1., 0., 1., 0., 1.]])

In [12]:
x = torch.rand(5, 5)
_, b = x.topk(3, 1, True, True)
print(x)
b


tensor([[0.3682, 0.9768, 0.3181, 0.2017, 0.5259],
        [0.9417, 0.8504, 0.6105, 0.5483, 0.8460],
        [0.6101, 0.2596, 0.3017, 0.8530, 0.3457],
        [0.9239, 0.7864, 0.5935, 0.5751, 0.6891],
        [0.4261, 0.1124, 0.5789, 0.4499, 0.1408]])


tensor([[1, 4, 0],
        [0, 1, 4],
        [3, 0, 4],
        [0, 1, 4],
        [2, 3, 0]])

In [14]:
from tqdm import tqdm
import time

text = ""
for char in tqdm(["a", "b", "c", "d"]):
    time.sleep(0.25)
    text = text + char
print(text)

100%|██████████| 4/4 [00:01<00:00,  3.80it/s]

abcd
