In [80]:
import numpy, soundfile
from scipy import signal
import torch

import torch.nn as nn
import torch.nn.functional as F

length = 200 * 160 + 240
audio, _ = soundfile.read('6.wav')
audio = audio[: length]
audio = numpy.stack([audio], axis=0)
rir, _ = soundfile.read('Room200-00001.wav')
rir = numpy.expand_dims(rir.astype(numpy.float), 0)
rir = rir / numpy.sqrt(numpy.sum(rir ** 2))
audio = signal.convolve(audio, rir, mode='full')[:, :length]
audio = torch.FloatTensor(audio[0])
inp = audio.unsqueeze(0)
inp = inp.unsqueeze(0)
print(inp)
inp = inp + inp
inp



tensor([[[1.7544e-18, 8.7721e-19, 1.0527e-18,  ..., 1.1737e-03,
          8.4053e-04, 8.8358e-04]]])


C:\Users\Kan\AppData\Local\Temp\ipykernel_8956\668286731.py:13: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  rir = numpy.expand_dims(rir.astype(numpy.float), 0)


tensor([[[3.5089e-18, 1.7544e-18, 2.1053e-18,  ..., 2.3473e-03,
          1.6811e-03, 1.7672e-03]]])

b: tensor([[[2]],

        [[2]],

        [[1]],

        [[2]]])
c: tensor([[[0, 1, 2, 3]]])
mask: tensor([[[False, False, False,  True]],

        [[False, False, False,  True]],

        [[False, False, False, False]],

        [[False, False, False,  True]]])


torch.Size([4, 1, 4])

tensor([[False, False, False,  True],
        [False, False, False,  True],
        [False, False, False, False],
        [False, False, False,  True]])


torch.Size([4, 4])

torch.Size([1, 1, 32240])